version: '3'
services:
  app:
    build: ./app/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./db/env_file
    expose:
     - 5000
    depends_on:
      - db
#    networks:
#      - web_nw

  web:
    build: ./web/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"    # map (host port : container port)
    depends_on:
      - app
#    networks:
#      - web_nw
#      - db_nw

  db:
    build: ./db/
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./db/env_file
    volumes:
      - "dbdata:/var/lib/postgresql/data"
#    networks:
#      - db_nw

volumes:
  dbdata:

#networks:
#  web_nw:
#    driver: bridge
#  db_nw:
#    driver: bridge